### ISSUE TITLE
a problem when you respawn

### ISSUE THREAD

**Issue by YoMyBoy** [Nicksf13/zombieplague#292]
I discovered a bug when you don't take the same weapon, the game thinks you took the same one and as soon as you shoot it, it merges with the other weapon, do you think you can fix it?

**Comment by Nicholas-Fuchs** [comment]
You mean, you shot with the same power as the other gun? Do you think that you can create a video for that? Or at least a step by step to reproduce it?

**Comment by YoMyBoy** [comment]
https://youtu.be/NVEDpYb48vU 
sorry for the late and the quality of the video , i will try to do my best to get better quality

**Comment by Nicholas-Fuchs** [comment]
I still didn't understand what is happening

**Comment by YoMyBoy** [comment]
well i fix it

**Comment by Nicksf13** [comment]
Closing the issue
