### ISSUE TITLE
problem with the sound

### ISSUE THREAD

**Issue by YoMyBoy** [Nicksf13/zombieplague#293]
the game mode can't find the sounds when normally it should find the file

**Comment by Nicholas-Fuchs** [comment]
Can you describe the steps to reproduce or at least the error log?

**Comment by YoMyBoy** [comment]
Failed to load sound "zombieplague\win_zombies3.mp3", file probably missing from disk/repository

**Comment by Nicholas-Fuchs** [comment]
Well, this seems like this file is missing on your serve. Can you give a look?

**Comment by YoMyBoy** [comment]
so it's got fixed idk how but it's got and before , in the console he don't find the sound folder but i try to change the path but not work

**Comment by Nicksf13** [comment]
Closing the issue
