### ISSUE TITLE
Problem with admin playermodels

### ISSUE THREAD

**Issue by YoMyBoy** [Nicksf13/zombieplague#294]
Admin playermodels zombie/humains not work by changing cvars , it's broken the game.

**Comment by Nicholas-Fuchs** [comment]
Oh, this is not exactly a bug. By default they are "", you need to fill this value. But I will make a change to solve this

**Comment by Nicholas-Fuchs** [comment]
Fixed on: https://github.com/Nicholas-Fuchs/zombieplague/tree/ZP-294, can you test it for me?

**Comment by YoMyBoy** [comment]
it's work ty

**Comment by Nicksf13** [comment]
https://github.com/Nicksf13/zombieplague/tree/ZP-296-fix - I had to fix this branch, I discovered a flaw on the player models. Can you check for me if there's any bug?

**Comment by Nicksf13** [comment]
?

**Comment by Nicksf13** [comment]
Waiting testing
