### ISSUE TITLE
About zombie knife

### ISSUE THREAD

**Issue by YoMyBoy** [Nicksf13/zombieplague#295]
Can you make a things that i can use different knife for a type of zombie ?

**Comment by Nicksf13** [comment]
It's already on the gamemode

You need to override the zombie class WeaponGive function

`function ZombieClass:WeaponGive(ply)
		ply:GiveZombieAllowedWeapon("someweaponId")
end`

Something like that

**Comment by Nicksf13** [comment]
Closing the issue, you can reopen if you want
